name: backtest_app #Environment name
dependencies:
  - python=3.8.5
  - pip:
    - dash
    - dash-renderer
    - dash-core-components
    - dash-html-components
    - plotly
    - numpy
    - datetime
    - scipy
    - pandas
    - psycopg2
    - dash
    - plotly
    - gunicorn # for app deployment
